### ISSUE TITLE
Errors im tex file

### ISSUE THREAD

**Issue by shoetten** [PattyDePuh/rtree#2]
Hey @PattyDePuh 
das tex file hat bei mir einige Fehler geworfen. Damit ich weiterarbeiten kann, hab ich insb alle \asc in \acs umbenannt.
Ich hoffe das war in deinem Sinne.
Grüße, Simon

**Comment by PattyDePuh** [comment]
Danke fürs Bereinigen,
die Fehler-Benachrichtigungen sind sowas von nichtsaussagend in WinShell >.<
Kompilieren und PDF erstellen tut er dennoch, daher hat es mich eigentlich nicht gestört.
