### ISSUE TITLE
Endspurt !

### ISSUE THREAD

**Issue by PattyDePuh** [PattyDePuh/rtree#3]
Abgabe Termin ist Mittwochabend.
Lass uns nochmal Gas geben ^^

**Comment by shoetten** [comment]
Jau. Welche Teile machst du fertig, was soll ich machen?
Du müsstest in deinen Teilen noch die ein oder andere Quellenangabe machen..

**Comment by PattyDePuh** [comment]
ich versuche das R*-Baum-Kapitel fertig zuschreiben.
ich würde mich von deiner Seite dann über Benchmark und Fazit freuen.

**Comment by PattyDePuh** [comment]
Wenn du meinst, dass Fazit und Benchmark fertig sind, würde ich mich ansonsten über das generelle Aufpolieren des Dokumentes freuen + Rechtschreibeprüfung (worin ich sonst immer "sucke") ^^

**Comment by shoetten** [comment]
Okay. Werd noch mal über meins drüber lesen und schauen ob ich noch was ergänze. Und dann check ich noch mal alles am Mittwoch und korrigier bzw mach den Stil etwas konsistenter..

**Comment by PattyDePuh** [comment]
Ich werde dann zusehen, dass ich bis spätestens morgen vormittag (11:59 Uhr) das Kapitel für den R*-Baum zuende geschrieben habe.
Kann ich dann davon ausgehen, wenn du morgen dann den letzten Schliff verpasst, dass du es dann auch das Ergebnis an Haunert schickst?

**Comment by shoetten** [comment]
jups, kla.

**Comment by PattyDePuh** [comment]
Mir fällt für das ReInsert()-Kapitel keine gescheite Abbildung ein. >.<
Sonst wäre es fertig.
